// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");

var discoveryWrap = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* [] */0
    ]);

var box = Css.style(/* :: */[
      Css.color(Css.red),
      /* :: */[
        Css.height(Css.vh(10.0)),
        /* :: */[
          Css.width(Css.vw(10.0)),
          /* :: */[
            Css.backgroundColor(Css.grey),
            /* :: */[
              Css.fontWeight(500),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

exports.discoveryWrap = discoveryWrap;
exports.box = box;
/* discoveryWrap Not a pure module */
